steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - gcr.io/$PROJECT_ID/notion-pdf-generator:$COMMIT_SHA
      - --file
      - services/notion-pdf-generator/Dockerfile
      - services/notion-pdf-generator

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/notion-pdf-generator:$COMMIT_SHA

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - notion-pdf-generator
      - --image
      - gcr.io/$PROJECT_ID/notion-pdf-generator:$COMMIT_SHA
      - --region
      - southamerica-east1
      - --platform
      - managed
      - --quiet

images:
  - gcr.io/$PROJECT_ID/notion-pdf-generator:$COMMIT_SHA
